improve launcher script

diff --git a/mx b/mx
--- a/mx
+++ b/mx
@@ -13,9 +13,11 @@ while [ -h "$_this_file" ]; do
     [[ $_this_file != /* ]] && _this_file="$_this_dir/$_this_file"
 done
 _this_dir=$(cd "$(dirname "$_this_file")" 2>/dev/null; pwd)
-_bin_dirs="$_this_dir:$(dirname $_this_dir)/cctbx/build/bin"
+_cctbx_bin="$(dirname $_this_dir)/cctbx/build/bin"
+_bin_dirs="$_this_dir:$_cctbx_bin"
 
-if [ -z "$1" ]; then
+# no args -> start subshell
+if [ "$#" = 0 ]; then
     echo -e "\033[1;36mMXconda bash subshell.\033[0;36m Ctrl-D to exit.\033[0m"
     # On Mac bash in a new terminal window is a login shell, but not on Linux.
     # Thus different sets of init files are executed.
@@ -35,23 +37,40 @@ if [ -z "$1" ]; then
                 PS1="\033[0;36m(mx)\033[0m$PS1"
                 PATH='"$_bin_dirs"':$PATH') \
         -i
-else
-    case "$1" in
-    install|remove|uninstall|update|upgrade|clean|info|search|list|config)
-        exec "$_this_dir"/conda "$@"
-        ;;
-    help|-h|--help)
-        cat <<EOF
+fi
+
+# subcommands
+case "$1" in
+install|remove|uninstall|update|upgrade|clean|info|search|list|config)
+    exec "$_this_dir"/conda "$@"
+    ;;
+help|-h|--help)
+    cat <<EOF
 mx is a simple launcher script. If the first argument is one of:
 install, remove, update, clean, info, search, list, config
 then the package manager (conda) is run. Type "mx conda -h" for details.
 With other arguments - the specified command is run.
 With no arguments - new bash shell is started with MXconda in the PATH.
 EOF
-        ;;
-    *)
-        PATH="$bin_dirs:$PATH"
-        exec "$@"
-        ;;
-    esac
+    exit
+    ;;
+esac
+
+if [ -e "$_this_dir/$1" ] || [ -e "$_cctbx_bin/$1" ]; then
+    PATH="$_bin_dirs:$PATH" exec "$@"
 fi
+
+echo "mx: $1: command not found..." >&2
+
+case "$1" in
+# programs with the same names as packages
+coot|pymol|probe|reduce)
+    echo "Hint: you need to install $1 first: mx install $1">&2
+    ;;
+dials.*|cctbx.*|mmtbx.*|xia2.*)
+    [ ! -e "$_cctbx_bin/cctbx.python" ] && \
+        echo "Hint: you need to install cctbx first: mx install cctbx">&2
+    ;;
+esac
+
+exit 1
